### PR TITLE
Bump build number to check that updating tokens worked

### PR DESCRIPTION
**Pull request by isuruf**
cc @ocefpaf, @jakirkham 

If this works, I'll start updating the other feedstocks

### CODE REVIEW

**Comment by ocefpaf** [comment]
I was doing the same by just restarting on master :smile:

**Comment by ocefpaf** [comment]
Let us merge this and see how master goes then :wink: 
(We will have a confirmation for CircleCI quicker than the rest.)

**Comment by ocefpaf** [comment]
CircleCI uploads are working: https://anaconda.org/conda-forge/obvious-ci/files

:tada: 

Awesome work @isuruf!!!

**Comment by isuruf** [comment]
Nice. Travis-CI also works. For appveyor it's the same secure string, so that'll work too, but appveyor is a bit backlogged for now. Is that okay?

**Comment by ocefpaf** [comment]
>  For appveyor it's the same secure string, so that'll work too, but appveyor is a bit backlogged for now. Is that okay?

Yeah, go for it. We need to bite the bullet deal with the backlog. (Let's take advantage of the weekend!)

**Pull request merged**
